### ISSUE TITLE
Question/Suggestion: Is this going to Adonis V5?

### ISSUE THREAD

**Issue by gusflopes** [QuantumLabsLtda/adonisjs-cerberus#9]
Hi, this looks like an awesome lib. Is this going to be migrated to v5? Is there any plan for that already?

There is only one missing piece for me (besides V5). In my case, I'm trying to make a similar logic or use this lib for a SAAS multi-tenant. Each company (client) have multiple users, but eventually a user can be user of another company also... So I have a `company_id` that I was thinking about adding.. not sure if it should be be on Role table or Permission table...

Not sure if this feature make sense for you, but I think it could be a good adition to this library...

**Comment by un-versed** [comment]
Hi!

We don't have any plans for migrating to v5 yet.

About your suggestion... 

I don't think this feature will make sense for everyone, because it's very specific...

But, my alternative is: you can create a resource for each company, and assign it to users.
